---
fixtures:
  repositories:
    gdm:
      repo: https://github.com/simp/pupmod-simp-gdm
      ref: 7.0.3
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    xinetd: https://github.com/simp/pupmod-simp-xinetd
  symlinks:
    vnc: "#{source_dir}"
